---
title: "Speicherorganisation"
date: 2025-06-28
date-format: DD.MM.YYYY
author: "Jacques Mock Schindler"
---

Informationen sind in Computern in Dateien gespeichert. Die
gespeicherten Informationen können dabei ganz unterschiedlicher Art, wie
zum Beispiel Texte, Bilder oder
Videos, sein.  
Als Modell, wie man sich Dateien vorstellen kann, hat sich das Bild von
Dossiers in Ordnern etabliert. Die einzelnen Dossiers sind die Dateien
und die Ordner sind die Strukturen, in denen die Dateien abgelegt sind.
Diese Konstruktion kann über mehrere Ebenen hinaus verschachtelt werde
(Ordner in Gestellen, die wiederum in einzelnen Räumen stehen, etc.).

## Dateinamen und Pfade

Damit Dateien identifiziert und gefunden werden können, müssen sie einen
Namen haben. Grundsätzlich gibt es keine Einschränkungen, wie Dateien
benannt werden. Die meisten Dateinamen bestehen allerdings aus
zwei Teilen: dem eigentlichen Dateinamen und der
Dateinamenserweiterung.

Der eigentliche Dateiname wird idealerweise so festgelegt, dass er einen
Rückschluss auf den Inhalt der Datei zulässt.  
Die Dateinamenserweiterung ist ein Zusatz, der Auskunft über den
Dateityp gibt. Sie steht hinter einem Punkt hinter dem eigentlichen
Dateinamen. Auf Windows Rechnern wird die Dateinamenserweiterung im
Dateimanager in der Standardeinstellung nicht angezeigt. Um dies zu
ändern, muss in den Einstellungen des Dateimanagers die Option
"Dateinamenerweiterungen anzeigen" aktiviert werden (Ansicht > Anzeigen > Dateinamenserweiterung). 

Damit Dateien besser ausgetauscht werden können, empfiehlt es sich, für
die Namen lediglich Buchstaben, Zahlen und Unterstriche (sog.
[ASCII](https://de.wikipedia.org/wiki/American_Standard_Code_for_Information_Interchange)-Zeichen)
zu verwenden. 

Damit man Dateien finden kann, muss man wissen, wo sie abgelegt worden
sind. Übertragen auf das Modell von Dossiers in Ordnern bedeutet das, zu
wissen, welches Dossier in welchem Ordner in welchem Gestell in welchem
Raum abgelegt ist. Wie in einem realen Archiv, geht man dabei vom Raum
zum Gestell, zum Ordner und schliesslich zum Dossier.
In der Informatik wird dieser Weg als Pfad bezeichnet. Auf einem
Windows-Rechner beginnt dieser Pfad mit dem sogenannten
Laufwerksbuchstaben, gefolgt von einem Doppelpunkt und einem Backslash
(`\`). Aus historischen Gründen ist der Laufwerksbuchstabe auf
Windows-Rechnern Standardmässig der Buchstabe `C`.

Ein Beispiel für einen Pfad könnte so aussehen:

```bash
C:\Users\fritz\Documents\text.docx
```

In diesem Beispiel ist `C:` der Laufwerksbuchstabe, `Users` der Ordner,
`fritz` der Unterordner, `Documents` der Unterordner von `fritz` und
`text.docx` die Datei, die im Ordner `Documents` abgelegt ist. `Users`
ist ein von Windows standardmässig angelegter Ordner, in dem die
persönlichen Daten der Benutzer abgelegt werden. Der Ordner `fritz` ist
der persönliche Ordner des Benutzers `fritz`. Der Ordner `Documents`
wird ebenfalls standardmässig von Windows im Ordner jedes Benutzers
angelegt. Dem Benutzer `fritz` steht es frei, diesen Ordner zu verwenden
und darin Dateien oder Underordner anzulegen.  
Der Dateiname `text.docx` verweist mit seiner Dateinamenserweiterung
`.docx` auf eine Datei, die mit dem Programm Microsoft Word erstellt
worden ist.

## Dateien in der Cloud

Dateien können nicht nur lokal auf dem Computer gespeichert werden.
Damit von überall und jederzeit auf Dateien zugegriffen werden kann,
werden Dateien in der *Cloud* gespeichert. Dabei handelt es sich um
Server in Rechenzentren, die über das Internet erreichbar sind.
Beispiele für solche Cloud-Dienst sind OneDrive von Microsoft oder
Google Drive.  
Ablageorte auf OneDrive werden in Windows direkt in der
Verzeichnisstruktur des Betriebssystems angezeigt, solche von Google
erhalten auf Windows einen eigenen Laufwerksbuchstaben (`G:\`).

Damit auf die Dateien in der Cloud zugegriffen werden kann, ist eine
Internetverbindung erforderlich.

## Dateistruktur für die Schule

Für den schulischen Bedarf erscheint es sinnvoll eine Dateistruktur nach
Fächern anzulegen. Im Ordner `Documents` wird dazu für jedes Fach ein
eigener Unterordner angelegt. Innerhalb der jeweiligen Fachordner kann
eine weitere Struktur nach Semester oder nach Thema sinnvoll sein. Ein
Beispiel für die Ordnerstruktur eines Erstklässlers an der KBW kann so
aussehen:

```txt
Documents\
         ├──Schule\
         |       ├──Deutsch
         |       ├──Franz
         |       ├──Mathe
         |       ├──WR
         |       └──...
         ├──Privat\
         |       ├──Rechnungen
         |       └──...
```

